spring:
  application:
    name: Softmind
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.hostinger.com
    port: 587
    username: suporte@atypicalgroup.com.br
    password: Suporte@typical2025
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
      uri: mongodb+srv://dba-softmind:DbaSoftmind%402025@project-fiap.2uqftjf.mongodb.net/?retryWrites=true&w=majority&appName=Project-Fiap
      auto-index-creation: true
      database: softmind

security:
  jwt:
    secret: softmind-super-secret-key-2025-strong!
    expiration: 86400000

tmdb:
  token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhOWYyY2E4YjZlZTBhNWUzOTI4YjhhZDM5ODc3ZGVjMCIsIm5iZiI6MTc1ODA2Mjg5Ny45MzYsInN1YiI6IjY4YzllOTMxZDA2ZGM0MjE2MGRlODBmZiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.EFBQ5RJCX_AaDACxgMzWNgmzFf3Syc0DNvWNhOiMlB0

server:
  port: 8000